@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNywiZXhwIjoxNjc5MzI2NTIxfQ.OBgbA39TlR2GpT8hzC1y1ZmU8rHFy58NnO3GMEz8fhU

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "rich@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "rich@test.com",
  "password": "password"
}

### Crafts Index
GET http://localhost:3000/crafts

### Crafts Create
POST http://localhost:3000/crafts
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "name": "Does it work?",
 "description": "testing 1, 2, 3",
 "materials": "testing 1, 2, 3",
 "difficulty": 3,
 "image_url": "test"
}

### Crafts Show
GET http://localhost:3000/crafts/9

### Crafts Update
PATCH http://localhost:3000/crafts/12
Authorization: Bearer {{jwt}}

{
 "name": "not mod pog",
 "description": "test",
 "materials": "testing 1, 2, 3",
 "image_url": "test",
 "image": "n/a"
}

### Crafts Destroy
DELETE http://localhost:3000/crafts/10
Authorization: Bearer {{jwt}}

#will test on frontend
# ### Comments Create
# POST http://localhost:3000/comments.json
# Authorization: Bearer {{jwt}}
# Content-Type: application/json
# {
#  "name": "Potato Doll",
#  "description": "A doll can be made with spuds, toothpicks, glue, paper scraps, googly eyes, and doll hair",
#  "materials": "potato, glue, toothpics, decorating supplies",
#  "image_url": "test"
# }